### ISSUE TITLE
Internet radio streams

### ISSUE THREAD

**Issue by ghost** [zgemma-star/servicehisilicon#1]
Hi,

Is it possible to play internet radio streams with default hisilicon player in h9.x series?
When i add radio url to channel list as 4097 service type i.e:
http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p
http://stream3.nadaje.com:9000/listen.pls
http://ice1.somafm.com/groovesalad-128-aac
i got black screen i have to reboot receiver to get picture back on tv channels.
The solution is to use gstplayer or extplayer, but i'm wondering if you could add radio streams support to default player.

**Comment by zgemma-star** [comment]
Thank you for the feedback.
We will check the content and try to make a working solution.

**Comment by ghost** [comment]
With the new OpenPLI 7.1 RC (new drivers and hisilicon player update) above links are working correctly with 4097 service ref.
Thanks.
