### ISSUE TITLE
Embedded Subtitles ( PGS)

### ISSUE THREAD

**Issue by Kerberos1864** [zgemma-star/servicehisilicon#2]
Dear Zgemma,
As you know PGS subtitles which come embedded with the movies are the new generation of subtitles which based on graphics not text. Default player is catching them in the movies but not showing them. If you can take this into consideration for making the H9S box better ! 
Best Regards,

**Comment by zgemma-star** [comment]
PGS subtitle is support in Enigma2?

I assume Kodi will work with PGS you can try with sample: https://drive.google.com/file/d/0BwxFVkl63-lEVEluSFZ4NlhpLUk/view?usp=sharing

**Comment by Kerberos1864** [comment]
Another issue regarding hisilicon service which I have to report to you Zgemma.
When using hisilicon service as original player we can't resume movies and series and can't see their progress times on EMC (Enhanced Media Center) which is problem related with ".cuts" file. Unless we remove the service hisilicon but this will make the playback bad. So please fix this.
Thanks in advance
System : OpenATV 6.2/6.3

**Comment by ozone1864** [comment]
> PGS subtitle is support in Enigma2?
> 
> I assume Kodi will work with PGS you can try with sample: https://drive.google.com/file/d/0BwxFVkl63-lEVEluSFZ4NlhpLUk/view?usp=sharing

You mean enigma2 doesn't support PGS subtitles ? and only KODI can play them ?

**Comment by Kerberos1864** [comment]
@zgemma-star as you see in drivers it supports PGS 
typedef enum hiFORMAT_SUBTITLE_TYPE_E
{
	HI_FORMAT_SUBTITLE_ASS = 0x0,    /**< ASS subtitle */
	HI_FORMAT_SUBTITLE_LRC,       /**< LRC subtitle */
	HI_FORMAT_SUBTITLE_SRT,       /**< SRT subtitle */
	HI_FORMAT_SUBTITLE_SMI,       /**< SMI subtitle */
	HI_FORMAT_SUBTITLE_SUB,       /**< SUB subtitle */
	HI_FORMAT_SUBTITLE_TXT,       /**< RAW UTF8 subtitle */
	_**HI_FORMAT_SUBTITLE_HDMV_PGS,      /**< pgs subtitle */**_

} HI_FORMAT_SUBTITLE_TYPE_E;

**Comment by zgemma-star** [comment]
Then it still depends on Enigma2 implementation.

Please discus further here: https://forums.openpli.org/topic/68209-exteplayer3-support-for-the-embedded-pgs-presentation-graphic-stream-subtitle-format/
