### ISSUE TITLE
Resume and Progress  Bar of Movies 

### ISSUE THREAD

**Issue by Kerberos1864** [zgemma-star/servicehisilicon#3]
Dear Zgemma,
When using hisilicon service as original player we can't resume movies and can't see their progress bar on EMC (Enhanced Media Center) which is problem related with ".cuts" file. Unless we remove the service hisilicon but this will make the playback bad. So please fix this.
Tried this on hundreds of videos files but still same problem on openATV
Thanks in advance
System : OpenATV 6.2/6.3

**Comment by zgemma-star** [comment]
Please ask EMC maintainer to fix this issue. It's not related to drivers
